name: mdsvex

on: [push, pull_request]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12]
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}        
      - run: yarn lint
        env:
          CI: true
          name: mdsvex

  build-test:
    name: test-build - node ${{ matrix.node-version }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [10, 12]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn test
      - run: yarn build
        env:
          CI: true
          name: mdsvex
